### ISSUE TITLE
Support for DLite

### ISSUE THREAD

**Issue by robertcsakany** [jacobalberty/firebird-docker#1]
I'm using Docker with DLite in macOSX. When I wanna use mounted databases - outside the Docker FS, it mouted as Volume with NFS, the database cannot connect or can be created with ISQL.

I've run this and it able to operate:

```
sed -i 's/#RemoteFileOpenAbility = 0/RemoteFileOpenAbility = 1/g' /var/firebird/etc/firebird.conf 
```

**Comment by jacobalberty** [comment]
The problem with simply enabling it is it's a safety feature and on Linux enabling it exposes a possible corruption issue. I may make a set of images to work with non Linux systems that default to having that enabled.

**Comment by robertcsakany** [comment]
Thank you. It makes sense.

**Comment by jacobalberty** [comment]
Revisiting this issue since I finally started the dynamic tag names.

Does this issue also apply to 3.0? or is it strictly a 2.5 issue?
