### ISSUE TITLE
Alpine image?

### ISSUE THREAD

**Issue by fdcastel** [jacobalberty/firebird-docker#10]
It would be possible to build an image based on [alpine](https://hub.docker.com/_/alpine/)?

I know it can bring some problems. MySql [won't do it](https://github.com/docker-library/mysql/issues/179). PostgreSQL [did it](https://github.com/docker-library/postgres/blob/dd88d2f02ad0f9852a7b33a8b542e14f5867b0c1/9.6/alpine/Dockerfile).

BTW: Thanks for the good work! 👍

**Comment by jacobalberty** [comment]
I would love to build it, I poked around a little and couldn't get a build environment working for firebird 3.0, I personally believe alpine images are of limited value as docker does a copy on write layout, so if your base image is debian:jessie for multiple images, then debian:jessie only gets downloaded once and only exists on the filesystem once, so shrinking your base image from 150mb to 20mb only saves you 130mb once even if you have 50 images descending from it. 

At work where I use these images I have a lot of images descended from debian:jessie, many of them from the docker library so I can't break my debian:jessie dependency for them so sticking with jessie is an advantage to me personally. That said I would like to try and get something like 3.0-alpine going, and even 3.0-centos (or 3.0-rhel if an official image is ever available on the hub). I will happily accept any pull request that accomplishes any of those, and in my free time I am slowly working on getting them together on my own.

**Comment by fdcastel** [comment]
Nicely said. Thank you for the elaborate explanations. 

I see your point about the layered image system. Even then I can see two advantages in a reduced version:

  - Reduced attack surface area: All other things being the same, the less the better.

  - Content distribution: 1 user having 50 different images is not the same as 50 users having 1 image. The download server pressure would be greatly reduced in the second case.

My sheer interest in this case is purely educational, as I'm currently not using Firebird on Docker (but would surely use it in the future). Hence, my suggestions/questions. Also, I greatly appreciate your practical expertise on the subject.

**Comment by jacobalberty** [comment]
I have made some headway on alpine support, but it still fails to build, segmentation fault when building msg.fdb, gives me an error about a file that shouldn't exist yet doesn't exist yet. May be something simple like adding a missing package, uploading what I have should someone else be able to figure it out. see the 3.0-alpine branch

**Comment by jacobalberty** [comment]
To anyone interested

3.0-alpine branch builds and passes travis-ci tests, at this time i'm not comfortable with it being tagged on the hub, it's pretty non standard compared to the original source. Requires changes to be compatible with c++11, musl and for some reason parallel builds were broken. the alloc and narrowing patches come from suse, the parallel build patch comes from debian and the musl patch comes from me.

the files necessary to build it are up under the branch 3.0-alpine but for now I am not letting it build and tag on the docker hub.
