### ISSUE TITLE
Firebird 5 image?

### ISSUE THREAD

**Issue by MaceWindu** [jacobalberty/firebird-docker#108]
Hello. Could you please add Firebird 5 support?  beta 1 was released recently

**Comment by jacobalberty** [comment]
Initial image should be up on i think the `5.0` tag shortly. I have not tested running it at all beyond just the build step test i need to spend a bit more time tweaking it before its ready to call one.

Sorry for the delay my previous job used this image so I was able to maintain it as part of my job. Current one does not so I'm a bit more delayed here.

I'm going to take another look at revising this build system and see if I can streamline it to make updates easier.

**Comment by jacobalberty** [comment]
Closing since fdcastel has taken over images
