### ISSUE TITLE
Databases file location (/databases)?

### ISSUE THREAD

**Issue by fdcastel** [jacobalberty/firebird-docker#12]
Just throwing some ideas:

  * `/var/lib/firebird` - The more [standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) one (albeit longer) 
  * `/opt/db` - shorter. Somewhat standard.
  * `/db` - even shorter. Not standard.

**Comment by jacobalberty** [comment]
There's nothing specific to /databases requiring it to used for storing the database files you could put them wherever you want firebird doesn't restrict that and the configuration file included doesn't. Perhaps I could change the default configuration to include database path restriction and swap out to using a path like that. Interestingly the only path mentioned in databases.conf outside of the macro substitution is "big = /databases/bigdb.fdb" firebird just doesn't really care where you put the databases, the only reason to restrict is for security purposes and not some limitation of firebird.

I'll evaluate adding
`DatabaseAccess = Restrict /somepath`
later on.
as far as following the filesystem hierarchy standard, the biggest feature there is making it easier to add and remove packages for end users, docker images are intended to be static from an end user perspective so you in theory don't need the advantages of that standard, mapping them to someplace standard on the host filesystem is going to be more important.

**Comment by jacobalberty** [comment]
Oh yeah perhaps on a broader filesystem scope I will also be redoing the filesystem layout in the images to closer match the compilation options for the official binaries provided on firebirdsql.org, which means moving the actual firebird binaries into /opt/firebird . I haven't yet decided what to do about the configuration files though as I like having them in their own separate directory from the rest of the binaries so it can be it's own volume. I'll either have an exception for those files being outside of $PREFIX like I do now, or i'll symlink from within $PREFIX to /var/firebird to maintain those paths.

**Comment by jacobalberty** [comment]
Precursor to moving the path is done, it can be changed with two edits in the Dockerfile now, the ENV DBPATH and the volumes line, I also went ahead and restricted DatabaseAccess to the contents of DBPATH (/databases for now)

**Comment by mrotteveel** [comment]
The `DBPATH` environment variable is currently not documented. It might be worthwhile to document it.

**Comment by jacobalberty** [comment]
@mrotteveel yeah, theres a bit of a minor overhaul I need to make. Best practices have evolved a bit since this was last updated
