### ISSUE TITLE
request for firebird 4.0.4 image

### ISSUE THREAD

**Issue by level420** [jacobalberty/firebird-docker#123]
@jacobalberty I really appreciate your work! I'd like to ask If it would be possible to publish images for firebird 4.0.4. That would be great! I've seen that you're working on the firebird 5 image which raised my hopes that you could also release an image of the current version 4. Thank you in advance for your help!

**Comment by level420** [comment]
@jacobalberty any hope that a 4.0.4 version will be released?  Thank you in advance for your help!

**Comment by philippweidhas** [comment]
Hey, same for me. I would need 4.0.4 or 4.0.3 running in docker. Do you have any plans for that? Thanks alot for your help!
