### ISSUE TITLE
Provide a Classic Server image version

### ISSUE THREAD

**Issue by betonetotbo** [jacobalberty/firebird-docker#26]
The currently images available are for:
- Super Server
- Super Classic

There is no Classic Server, please can you provide it?

**Comment by jacobalberty** [comment]
Classic server requires inetd within the container. I have not looked into running inetd within a docker container at all and it contains a bunch of caveats. I am willing to make an image that does it though, it just doesn't fit with  usage at all. If you're willing to test it when I get a test image going and verify it works properly then absolutely, this week is very busy for me but next week I will be able to start on it.

**Comment by betonetotbo** [comment]
I'm trying by myself with https://github.com/pataquets/docker-xinetd . I'll post here some infos about it .

**Comment by betonetotbo** [comment]
I have published my image for Firebird Classic Server https://hub.docker.com/r/betonetotbo/docker-firebird-cs/
