### ISSUE TITLE
Firebird database commands to connect

### ISSUE THREAD

**Issue by ircross** [jacobalberty/firebird-docker#30]
How can I get into the Firebird database command line to show databases and run commands similar to SQL. I have tried multiple commands with no luck. Thank you in advance.

**Comment by wmakley** [comment]
@ircross, are you trying to connect using isql on your local machine, or within Docker?

**Comment by ircross** [comment]
I was trying within the docker container and just started working on migrating one of our firebird databases to docker. I am not familiar with isql without docker. I am getting familiar with docker but first time working on a firebird database.

**Comment by wmakley** [comment]
Okay, so there is full documentation elsewhere, but:

- **isql** is the firebird command line tool
- It connects to databases using a path to the database file. This will require some trial and error, but it looks like: `isql localhost:/path/to/db -u USER -p PASSWORD`
- If you expose the docker image's port 3050 to your local machine, you can install isql locally and connect to it by adding the port number: `isql localhost:3050:/path/to/db -u USER -p PASSWORD` (This is probably the easiest)
- If you want to run isql within docker, you will just want to run something like the first command I gave you within the container.

**Comment by ircross** [comment]
I will try the solutions when I get to the office. Thanks I initially was trying writhing the container but isql wasn’t a recognizable command. Appreciate the assistance!
