### ISSUE TITLE
Unable to complete network request to host "localhost" from isql

### ISSUE THREAD

**Issue by SoerenHenning** [jacobalberty/firebird-docker#39]
Using the `2.5-ss` image, I cannot query the database via `isql` as I'm getting an error saying that no networks requests to localhost can be made.

I'm starting a container via:

```shell
docker run -it -e "ISC_PASSWORD=masterkey" -e "FIREBIRD_DATABASE=test.gdb" -e "FIREBIRD_USER=test" -p 3050:3050  -v /tmp:/firebird/data --name firebird --rm jacobalberty/firebird:2.5-ss bash
```

Output is:

```
Warning - maximum 8 significant bytes of password used
setting 'test' password to 'f6a26ebc667b433f2bc6'
Use CONNECT or CREATE DATABASE to specify a database
```

Then I'm running:

```sh
cd /usr/local/firebird/bin
./isql ${DBPATH}/test.gdb -u test -p f6a26ebc667b433f2bc6
```

Which yields:
```
Statement failed, SQLSTATE = 08006
Unable to complete network request to host "localhost".
-Failed to establish a connection.
Use CONNECT or CREATE DATABASE to specify a database
```

I tested the same sequence of executions with `2.5.7-ss` and `2.5.6-ss`. While the error also exists in`2.5.7-ss`, in `2.5.6-ss` everything works fine. (Note that in the latter the interactive shell has to be started separately.)

**Comment by SoerenHenning** [comment]
Okay, I see what the problem is. `docker run -it [...] bash` overwrites the `CMD`, which starts the server. Therefore, there seems to be nothing wrong with the Docker image. However, may it be reasonable to change this behavior? (E.g., start the server in the entrypoint?) I'm not sure what good Docker practices are in this context.

**Comment by mrotteveel** [comment]
This seems to be the same problem as #33
