### ISSUE TITLE
When creating the firebird container can you create the tables from as postgresql ??

### ISSUE THREAD

**Issue by carlosvargas31** [jacobalberty/firebird-docker#44]
Hello, I would like to know if the isql command that I handle in windows also works when I use firebird with Docker, because I was looking inside the container with the 'docker exec -it firebird bash' command but the ./isql does not appear can you help me please
docker run --name firebird -p 3050: 3050 -e ISC_PASSWORD = masterkey -v $ (pwd) opt / dbp: / var / lib / firebird / data -d jacobalberty / firebird 
I leave this information on how to create my container in case you need ....

**Comment by jacobalberty** [comment]
isql is in /usr/local/firebird/bin I should probably modify the default PATH for the container to include /usr/local/firebird/bin . In general though you'd want to run isql from outside the container and just use the server inside the container but I do understand sometimes it's easier to just work inside.

**Comment by carlosvargas31** [comment]
Oh brother thank you very much, but in conclusion you can only create and connect entering the firebird container of the docker ..... Although I don't think it bothers too much it is just one more command.
Thanks for your help
