### ISSUE TITLE
[FEATURE REQUEST] FIREBIRD_ALIASES variable

### ISSUE THREAD

**Issue by silvioprog** [jacobalberty/firebird-docker#47]
Hi.

It would be nice to allow some variable for [aliasing configuration](https://firebirdsql.org/rlsnotesh/config-db-alias.html), for example:

```
... -e FIREBIRD_ALIASES 'MYDB=/some/long/directory;MYOTHERDB=/some/other/long/directory' ...
```

this way, outside container, we could access the database using the aliases `MYDB` and `MYOTHERDB` instead of their path.

Maybe the official `registerDatabase.sh` (available at `/usr/local/firebird/bin/`) could help to implement this feature.

Thank you!

**Comment by jacobalberty** [comment]
I have added what is hopefully a working implementation of this, give it a try and let me know if it works.

Use FIREBIRD_ALIASES as the environment variable format FIREBIRD_ALIASES='ALIAS=path/to/your.fdb;ALIAS2=path/to/other.fbd'

I'm simply calling registerDatabase.sh and right now it is only in the 3.0 branch. It should be trivial to bring to 4.0. 2.5 will require calling createAliasDB.sh but shouldn't be much work to move over once I've confirmed it works in 3.0.

**Comment by silvioprog** [comment]
Nice job! :-)

I'm going to test it and back with feedback ...

**Comment by silvioprog** [comment]
Tested and worked like a charm! 🎉 Thank you very much again for implementing! :-)

**Comment by silvioprog** [comment]
It would be nice to add some documentation for `FIREBIRD_ALIAS` feature in the README file. :-)

**Comment by woodingkev** [comment]
Sorry for bumping closed issue. Any chance the update to bring this to 2.5 could be done?
