### ISSUE TITLE
I can't connect to a database inside docker

### ISSUE THREAD

**Issue by AndreiTS** [jacobalberty/firebird-docker#48]
Firebird 3.0.4

127.0.0.1:
![docker1](https://user-images.githubusercontent.com/13489837/70350194-0857c000-1845-11ea-89e4-9c9a4a4a9f95.png)

192.168.99.100:
![docker2](https://user-images.githubusercontent.com/13489837/70350195-0857c000-1845-11ea-9ee9-158afe41dec7.png)

The database is in /firebird/data/immobile.fdb
![docker3](https://user-images.githubusercontent.com/13489837/70350196-08f05680-1845-11ea-9818-2720c7028e42.png)

**Comment by AndreiTS** [comment]
I'm using DBeaver to connect. The password is from /firebird/etc/SYSDBA.password

**Comment by agerrits** [comment]
I seem to have the same issue. Running the docker file on a Synology and set the environment with the password and database to start with. 
Using IBExpert and it is not able to get to the database. Ports are opened and set to standard. (I used other ports first but same result)
It keeps saying "" connection not established. Connection rejected by remote interface.
![2019-12-06_19h44_22](https://user-images.githubusercontent.com/17658887/70368565-17e50200-1861-11ea-96e0-64e12053d47c.jpg)

Trying with TMS Data Modeler same result on another machine

Here are the settings from the docker instance (which is running)
![2019-12-06_19h51_43](https://user-images.githubusercontent.com/17658887/70368629-f1739680-1861-11ea-8657-6219fb1733c7.jpg)

**Comment by agerrits** [comment]
Update.
The reason why the client can't logon is related to the fbclient.dll in this case. The application needed the 32bit version and now connects correctly. Still need to do some more setting but this issue is resolved for me.

**Comment by AndreiTS** [comment]
@agerrits Can you explain how did you make it work?

**Comment by AndreiTS** [comment]
Docker is hard. After sometime I have discovered that I need to run this command: 
docker run --detach --publish 3050:3050 --name fb jacobalberty/firebird

Now I can connect to localhost:3050
