### ISSUE TITLE
GDSExecption using jaybird 3

### ISSUE THREAD

**Issue by Cristoto** [jacobalberty/firebird-docker#50]
When I try to make a query from my java application using the jaybird 3x library, it returns the following error. I'm using firebird:2.5.6-sc on my Dockerfile.

![error](https://user-images.githubusercontent.com/19151793/72970856-5fe3c800-3dc0-11ea-8d46-48ec5a901477.png)

My docker compose use a personal image that added extra directories to server.

![image](https://user-images.githubusercontent.com/19151793/72971179-22336f00-3dc1-11ea-9d91-851daa709838.png)

**Comment by mrotteveel** [comment]
This exception normally indicates that the port isn't open on 176.31.126.202, but without a full stacktrace, I can't say that with 100% certainty.

**Comment by Cristoto** [comment]
The port 3050 is open because I can connect using flamerobin for example.

**Comment by Cristoto** [comment]
Exactly, it was problem for port.
Thank you!!
