### ISSUE TITLE
How dow I override uidnumber and gidnumber of the firebird user?

### ISSUE THREAD

**Issue by level420** [jacobalberty/firebird-docker#53]
I need to have the possibility to specify the uidnumber and gidnumber of the firebird user inside the container.

What I've tried so far is to move `/etc/passwd` and `/etc/group` from within the image outside, then change the uidnumer for firebird from 84 to 999 in `/etc/passwd` and the gidnumber from 84 to 999  in `/etc/group`.

Then I've mounted them via -v to their paths in the container
```
-v /some/path/passwd:/etc/passwd -v /some/path/group:/etc/group
```
But still when connecting to the running container via `docker exec -ti mycontainername bash`, and create a file, e.g. `touch /tmp/bla` the file gets user.group 84.84.

Asking the uidnumer, gidnumber via `id firebird` results in
```
uid=999(firebird) gid=999(firebird) groups=999(firebird)
```

I know this may be not per se related to the firebird docker image, but maybe somebody solved this alreads.

Thank you for helping
Kind regards

**Comment by mrotteveel** [comment]
Out of curiosity: why do you need this?

**Comment by level420** [comment]
@mortteveel I just want to replace an existing firebird installation on centos 7 and to get par with uidnumber and gidnumber present on the docker host. I'm starting the container via systemd.
