### ISSUE TITLE
How to change/set the default firebird.conf file automatically.

### ISSUE THREAD

**Issue by siwalan** [jacobalberty/firebird-docker#55]
Hi all,

For certain cases of my firebird container. We need some of them running in different port. This can be accomplished with changing the firebird.conf.

However. Even after I do a docker commit on the container instance where I have changed the firebird.conf, initializing a new container based on the new image commit still result in the same old, original version of firebird.conf. Is there any way that it can be changed? Personally, I think it is related to the docker-entrypoint.sh file.

Any help would be greatly appreciated!

Cheers,

**Comment by mrotteveel** [comment]
Out of curiosity: why do you need to change the port in the image?

The normal way of handling this is changing the port mapping when you run the image, that way the port inside the image can remain the same, while the port exposed to the outside world can be different.

**Comment by siwalan** [comment]
@mrotteveel 

One of our legacy enterprises app requires Firebird to work at port 3051.

I need to find a way to do it automatically, preferably without any human intervention, because in most cases the regular and remote site user may need to be able to kill and create a new container.

Background: The ERP software (and/or Firebird) often stuck/crashes and require full system reboot. A mere reload of the firebird would not work (previous sys-admin had tried this, it will only work again on full system reboot). We are dockerizing the firebird to enable us reboot Firebird without rebooting the entire system.


Thanks for the tip though, will try to think more about it later.


Cheers,

**Comment by mrotteveel** [comment]
Where is that legacy application running in relation to the container with Firebird? In the same container, in a different container, on the host system? What are you using to orchestrate this (docker-compose, something else)?

**Comment by jacobalberty** [comment]
All you should need to do is create a volume for /firebird then edit the firebird.conf file in the etc sub folder under that volume.

**Comment by siwalan** [comment]
> Where is that legacy application running in relation to the container with Firebird? In the same container, in a different container, on the host system? What are you using to orchestrate this (docker-compose, something else)?
> 
> BTW: requiring a full system reboot to solve problems with Firebird that aren't solved with a process restart sounds a bit odd.

The legacy app are located at the client side. And I'm planning to use docker-compose.

Yes, I have to admit that it is a bit odd. But it works. Restarting the client app won't work, reloading the database won't work. But rebooting the entire Firebird servers work. Keep in mind that the application is client side so the only thing located at the server is Firebird. 

I wish that I can investigate more about this but unfortunately the vendor encrypted/locked the entire legacy databases.

**Comment by siwalan** [comment]
> All you should need to do is create a volume for /firebird then edit the firebird.conf file in the etc sub folder under that volume.

Thanks! Will try this.

**Comment by mrotteveel** [comment]
In any case, if you are starting it with docker right now, then using `-p 3050:3051` will expose the port `3050` of the image as port `3051` to the outside world, see also [Container networking](https://docs.docker.com/config/containers/container-networking/). You can do something similar in docker-compose:

```
ports:
  - "3050:3051"
```
(see docker-compose documentation for details)

**Comment by mrotteveel** [comment]
In my previous comment I had initially the wrong order (for some reason I always do this...), the correct order is `-p 3051:3050`.
