### ISSUE TITLE
Can not find isql on lastest

### ISSUE THREAD

**Issue by handl3r** [jacobalberty/firebird-docker#61]
Hi jaco,
I can not find isql in lastest image now
we need isql to query to databases

**Comment by mrotteveel** [comment]
Could you please provide a reproducible example of what you are trying (and exactly which image you're pulling). For the 3.0.6 image, I can find isql in `/usr/local/firebird/bin`.

**Comment by handl3r** [comment]
@mrotteveel  Hi mrotteveel.
Sorry about this issues. After double-check, i found it.
Thanks for your response. Good job
