### ISSUE TITLE
Firebird binaries are not on $PATH

### ISSUE THREAD

**Issue by iget-master** [jacobalberty/firebird-docker#68]
Trying to running any firebird binary like `gbak` is frustrated by incomplete $PATH.

Since the binaries are inside `/usr/local/firebird/bin`, this path should be on $PATH?

**Comment by Microcom-Bjarne** [comment]
running commands from PS with the environment PATH setup works for me ...
`docker exec -e PATH=/usr/local/firebird/bin <containername> gbak <your options here>`
