### ISSUE TITLE
docker apt-get - unable to install packages

### ISSUE THREAD

**Issue by Kagu-chan** [jacobalberty/firebird-docker#69]
If i use the master (v3.0) Dockerfile to extend from, i cannot install git.

```
FROM jacobalberty/firebird:v3.0

RUN apt-get update && \
    apt-get install -y curl git;
[...]
```

Installation fails with last attempt to install or configure `netbase`.
```
Running hooks in /etc/ca-certificates/update.d....done.
Errors were encountered while processing:
 netbase
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Seems unrelated to the debian package used, as the following works
```
FROM debian:jessie

RUN apt-get update && \
    apt-get install -y curl git
```
git is required for some npm installations in our project

**Comment by jacobalberty** [comment]
This has to do with the entry firebird added to /etc/services
You'll need to add the relevant dpkg options, something like do `apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew curl git`  will get git and curl installed, you won't have the relevant service entries netbase wanted to install though, if this becomes an issue the file netbase wanted to install is available in /etc/services.dpkg-dist you could just append that file on to the end of /etc/services and have a working combined file.
