### ISSUE TITLE
Firebird POST_EVENT problema with docker

### ISSUE THREAD

**Issue by MatheusRivello** [jacobalberty/firebird-docker#85]
Hello, 

First I would like to thank you for the solution, the firebird container helped me a lot.

I searched about this bug and didn't find any solution. I have a problem with a POST_EVENT when my database is controlled by firebird in docker. The event is not fired and I have this return. I associated my host's port 3062 with the container's 3050

```
Debugger Exception Notification

Project Clients.exe raised exception class EIBNativeException with message '[FireDAC][Phys][FB]Unable to complete network request to host "MY_DNS".
Failed to establish a secondary connection for event processing.
No connections could be made because the target machine actively refused them. '.
```

If I try with a virtual machine with firebird installed normally, the event works.

Thanks for your attention

**Comment by mrotteveel** [comment]
This is covered in the readme, see https://github.com/jacobalberty/firebird-docker#events

**Comment by jacobalberty** [comment]
I believe `RemoteAuxPort` will also need to be the same on both sides of the port mapping, ie if you set `RemoteAuxPort`  to 4050 you'll need to map port 4050 to 4050.

**Comment by mrotteveel** [comment]
@jacobalberty Yes, you're right! The server sends the port the client should use, so it will need to match.

**Comment by MatheusRivello** [comment]
@jacobalberty @mrotteveel Thanks for the help. In fact the ports need to be the same to work. I ran tests and it worked.
