### ISSUE TITLE
python3-pip unable to install due to netbase error

### ISSUE THREAD

**Issue by findjonmos** [jacobalberty/firebird-docker#86]
Hello all,

I have the following Dockerfile:

`FROM jacobalberty/firebird:2.5-sc

RUN apt-get update && apt-get -y install python3 python3-pip

WORKDIR /usr/src/dapi-pytest

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . /usr/src/dapi-pytest

CMD [ "python3.9", "./test.py" ]`

When I run the build command it starts to build the image but will fail after a minute or two with the following error message:

`#6 35.44 Updating certificates in /etc/ssl/certs...
#6 35.84 0 added, 0 removed; done.
#6 35.84 Running hooks in /etc/ca-certificates/update.d...
#6 35.84 done.
#6 35.90 Errors were encountered while processing:
#6 35.90  netbase
#6 35.93 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
executor failed running [/bin/sh -c apt-get update && apt-get -y install python3 python3-pip]: exit code: 100`

Aim:
My aim is to have a docker image that can run Firebird 2.5 alongside Python 3.9, Pytest and a few other dependencies (FDB 2.0.2) so that I can run automation tests from a Continuous Integration environment that we have hosted locally at work.
 
My project makes calls to the Firebird database of the application under test to assert that data has been modified as required

If I remove python3-pip from the apt-get install line then the image will build without the error. I found that I am then able to open the docker container shell and install pip3 after the fact, but I need this done as part of the container build if its possible

I have tried using the firebird:2.5-sc, firebird:2.5-ss but I still get the same error

Is anyone able to help?

**Comment by jacobalberty** [comment]
Given netbase seems to be the most common source of issues with adding packages to the image, I'm going back and adding netbase. I'm getting 3.0 tonight, 2.5 is a little more involved to do new pushes on but I'll try to get it this weekend

**Comment by jacobalberty** [comment]
I have added `netbase `to the image you should be able to pull a new copy from docker hub and it work now.

@findjonmos can you confirm if the issue is fixed or not now?
