### ISSUE TITLE
Database already opened with engine instance, incompatible with current

### ISSUE THREAD

**Issue by mpassos11** [jacobalberty/firebird-docker#97]
Hi,

I'm trying to use firebird with a kind of load balancer. Using docker service I have created 5 firebird instances and I am trying to access this server from various places but every now and then the error happens:

`Database already opened with engine instance, incompatible with current`

Is there any way to work with firebird and docker with a load balancer?

I created the service in docker using the following command line:

`docker service create --name firebird -p 3050:3050 --replicas 5 --update-parallelism 5 -e ISC_PASSWORD=masterkey --mount type=bind,source=c:/vmulti,target=/firebird/data --limit-cpu="0.5" --limit-memory="10m" jacobalberty/firebird:3.0`

CPU and Memory limits were purposely changed for testing

**Comment by jacobalberty** [comment]
You can't share a single database with multiple instances of a database server. You need to setup replication. 3.0 does not have built in replication support so you'll need to check out [these tools](https://www.firebirdfaq.org/faq249/) . 4.0 [has built-in replication (see page 23)](https://firebirdsql.org/file/documentation/release_notes/Firebird-4.0.0-ReleaseNotes.pdf) but it's uni-directional, so your replicas will be reader instances not writer instances. It's alos not the same as just pointing the same instance at the same file. You need to build out the infrastructure and configure it, not just scale up replicas in docker.
